"""
Curated genre group definitions.

Each group maps a semantic category to a list of canonical genre names
(post-normalization). Genres can belong to multiple groups.

The member lists use normalized genre names — the populate script matches
them case-insensitively against the genres table.
"""

GENRE_GROUPS: list[dict] = [
    # --- Rock ---
    {
        "name": "rock",
        "display_name": "Rock",
        "description": "Rock music spanning all eras and subgenres",
        "sort_order": 1,
        "members": [
            "rock",
            "classic rock",
            "rock and roll",
            "pop rock",
            "pop/rock",
            "blues rock",
            "roots rock",
        ],
    },
    {
        "name": "alternative_rock",
        "display_name": "Alternative / Indie Rock",
        "description": "Alternative, indie rock, and college rock",
        "sort_order": 2,
        "members": [
            "alternative",
            "alternative rock",
            "indie",
            "indie-rock",
            "college rock",
            "lo-fi",
        ],
    },
    {
        "name": "punk",
        "display_name": "Punk",
        "description": "Punk rock and its subgenres",
        "sort_order": 3,
        "members": [
            "punk",
            "punk rock",
            "pop-punk",
            "hardcore punk",
            "hardcore",
            "post-hardcore",
            "skate punk",
            "oi",
        ],
    },
    {
        "name": "metal",
        "display_name": "Metal",
        "description": "Heavy metal and all subgenres",
        "sort_order": 4,
        "members": [
            "metal",
            "heavy-metal",
            "thrash-metal",
            "death-metal",
            "black-metal",
            "doom-metal",
            "nu-metal",
            "progressive-metal",
            "speed-metal",
            "power-metal",
            "stoner-metal",
            "sludge metal",
            "metalcore",
            "grindcore",
        ],
    },
    {
        "name": "hard_rock",
        "display_name": "Hard Rock",
        "description": "Hard rock, stoner rock, grunge",
        "sort_order": 5,
        "members": [
            "hard-rock",
            "stoner-rock",
            "grunge",
            "southern rock",
        ],
    },
    {
        "name": "progressive_rock",
        "display_name": "Progressive Rock",
        "description": "Prog rock, art rock, math rock, Canterbury scene",
        "sort_order": 6,
        "members": [
            "progressive-rock",
            "art-rock",
            "math-rock",
            "canterbury scene",
            "krautrock",
            "zeuhl",
        ],
    },
    {
        "name": "psychedelic",
        "display_name": "Psychedelic",
        "description": "Psychedelic rock, space rock, acid rock",
        "sort_order": 7,
        "members": [
            "psychedelic",
            "psychedelic-rock",
            "space-rock",
            "acid-rock",
            "neo-psychedelia",
            "stoner-rock",
        ],
    },
    {
        "name": "post_punk_new_wave",
        "display_name": "Post-Punk / New Wave",
        "description": "Post-punk, new wave, darkwave, gothic",
        "sort_order": 8,
        "members": [
            "post-punk",
            "new wave",
            "darkwave",
            "coldwave",
            "gothic",
            "gothic rock",
            "goth",
            "no wave",
            "post-punk revival",
        ],
    },
    {
        "name": "shoegaze_dream_pop",
        "display_name": "Shoegaze / Dream Pop",
        "description": "Shoegaze, dream pop, ethereal, noise pop",
        "sort_order": 9,
        "members": [
            "shoegaze",
            "dream-pop",
            "ethereal",
            "noise-pop",
            "slowcore",
            "sadcore",
        ],
    },
    {
        "name": "indie_pop",
        "display_name": "Indie Pop",
        "description": "Indie pop, chamber pop, twee pop, jangle pop",
        "sort_order": 10,
        "members": [
            "indie-pop",
            "chamber pop",
            "twee pop",
            "jangle pop",
            "power-pop",
            "britpop",
            "c86",
        ],
    },
    {
        "name": "garage",
        "display_name": "Garage Rock",
        "description": "Garage rock, proto-punk, garage revival",
        "sort_order": 11,
        "members": [
            "garage-rock",
            "garage",
            "proto-punk",
            "garage rock revival",
        ],
    },
    # --- Pop ---
    {
        "name": "pop",
        "display_name": "Pop",
        "description": "Pop music, mainstream and sub-categories",
        "sort_order": 12,
        "members": [
            "pop",
            "dance pop",
            "teen pop",
            "bubblegum pop",
            "europop",
            "k-pop",
            "j-pop",
        ],
    },
    {
        "name": "synth_pop_electronic_pop",
        "display_name": "Synth-Pop / Electropop",
        "description": "Synth-pop, electropop, new romantic",
        "sort_order": 13,
        "members": [
            "synth-pop",
            "electropop",
            "new romantic",
            "new romantics",
            "synthwave",
            "retrowave",
        ],
    },
    # --- Electronic ---
    {
        "name": "electronic",
        "display_name": "Electronic",
        "description": "Electronic music broadly",
        "sort_order": 14,
        "members": [
            "electronic",
            "electronica",
            "idm",
            "glitch",
            "experimental electronic",
        ],
    },
    {
        "name": "house",
        "display_name": "House",
        "description": "House music and subgenres",
        "sort_order": 15,
        "members": [
            "house",
            "deep-house",
            "acid-house",
            "electro-house",
            "tech house",
            "progressive house",
            "chicago house",
            "minimal",
        ],
    },
    {
        "name": "techno",
        "display_name": "Techno",
        "description": "Techno music and related styles",
        "sort_order": 16,
        "members": [
            "techno",
            "detroit techno",
            "minimal techno",
            "industrial techno",
            "acid techno",
        ],
    },
    {
        "name": "drum_and_bass",
        "display_name": "Drum & Bass / Jungle",
        "description": "Drum & bass, jungle, breakbeat",
        "sort_order": 17,
        "members": [
            "drum & bass",
            "jungle",
            "breakbeat",
            "breakcore",
            "liquid funk",
        ],
    },
    {
        "name": "ambient_chill",
        "display_name": "Ambient / Chill",
        "description": "Ambient, chillout, downtempo, new age",
        "sort_order": 18,
        "members": [
            "ambient",
            "chillout",
            "downtempo",
            "new-age",
            "drone",
            "dark-ambient",
            "chillwave",
        ],
    },
    {
        "name": "trip_hop",
        "display_name": "Trip-Hop",
        "description": "Trip-hop, Bristol sound",
        "sort_order": 19,
        "members": [
            "trip-hop",
            "bristol sound",
        ],
    },
    {
        "name": "dance_disco",
        "display_name": "Dance / Disco",
        "description": "Dance, disco, Eurodance, hi-NRG",
        "sort_order": 20,
        "members": [
            "dance",
            "disco",
            "nu-disco",
            "eurodance",
            "hi-nrg",
            "italo disco",
        ],
    },
    {
        "name": "experimental_avantgarde",
        "display_name": "Experimental / Avant-Garde",
        "description": "Experimental, avant-garde, noise, musique concrete",
        "sort_order": 21,
        "members": [
            "experimental",
            "avant-garde",
            "noise",
            "noise-rock",
            "industrial",
            "musique concrete",
            "sound art",
            "free improvisation",
        ],
    },
    {
        "name": "dub_dubstep",
        "display_name": "Dub / Dubstep",
        "description": "Dub, dubstep, post-dubstep",
        "sort_order": 22,
        "members": [
            "dub",
            "dubstep",
            "post-dubstep",
            "dub techno",
        ],
    },
    # --- Hip-Hop / R&B ---
    {
        "name": "hip_hop",
        "display_name": "Hip-Hop / Rap",
        "description": "Hip-hop, rap, and subgenres",
        "sort_order": 23,
        "members": [
            "hip-hop",
            "rap",
            "east coast hip hop",
            "west coast hip hop",
            "southern hip hop",
            "underground hip hop",
            "conscious hip hop",
            "gangsta rap",
            "trap",
            "boom bap",
            "old school hip hop",
        ],
    },
    {
        "name": "rnb_soul",
        "display_name": "R&B / Soul",
        "description": "R&B, soul, neo-soul, Motown",
        "sort_order": 24,
        "members": [
            "r&b",
            "soul",
            "neo-soul",
            "motown",
            "northern soul",
            "southern soul",
            "contemporary r&b",
            "quiet storm",
        ],
    },
    {
        "name": "funk",
        "display_name": "Funk",
        "description": "Funk, p-funk, go-go",
        "sort_order": 25,
        "members": [
            "funk",
            "p-funk",
            "go-go",
            "funk rock",
            "funk metal",
            "acid-funk",
        ],
    },
    # --- Jazz ---
    {
        "name": "jazz",
        "display_name": "Jazz",
        "description": "Jazz broadly — bebop, hard bop, swing, standards",
        "sort_order": 26,
        "members": [
            "jazz",
            "bebop",
            "hard-bop",
            "swing",
            "cool jazz",
            "modal jazz",
            "vocal jazz",
            "smooth jazz",
            "contemporary jazz",
            "jazz-piano",
            "jazz standards",
            "jazz-guitar",
            "big band",
        ],
    },
    {
        "name": "jazz_fusion",
        "display_name": "Jazz Fusion",
        "description": "Jazz fusion, jazz-funk, jazz-rock",
        "sort_order": 27,
        "members": [
            "jazz-fusion",
            "fusion",
            "jazz-funk",
            "jazz-rock",
            "acid-jazz",
        ],
    },
    {
        "name": "free_jazz_avantgarde",
        "display_name": "Free Jazz / Avant-Garde Jazz",
        "description": "Free jazz, avant-garde jazz, spiritual jazz",
        "sort_order": 28,
        "members": [
            "free jazz",
            "avant-garde jazz",
            "spiritual jazz",
            "free improvisation",
        ],
    },
    {
        "name": "latin_jazz",
        "display_name": "Latin Jazz",
        "description": "Latin jazz, Afro-Cuban jazz, bossa nova",
        "sort_order": 29,
        "members": [
            "latin jazz",
            "afro-cuban jazz",
            "bossa nova",
        ],
    },
    # --- Blues ---
    {
        "name": "blues",
        "display_name": "Blues",
        "description": "Blues and subgenres",
        "sort_order": 30,
        "members": [
            "blues",
            "classic blues",
            "delta blues",
            "chicago blues",
            "electric blues",
            "country blues",
            "blues rock",
            "british blues",
            "acoustic blues",
            "texas blues",
        ],
    },
    # --- Country / Folk / Americana ---
    {
        "name": "country",
        "display_name": "Country",
        "description": "Country, outlaw country, honky tonk, Nashville",
        "sort_order": 31,
        "members": [
            "country",
            "alt-country",
            "outlaw country",
            "honky tonk",
            "country rock",
            "country pop",
            "nashville sound",
            "country blues",
            "bakersfield sound",
        ],
    },
    {
        "name": "folk",
        "display_name": "Folk",
        "description": "Folk, folk-rock, singer-songwriter, acoustic",
        "sort_order": 32,
        "members": [
            "folk",
            "folk-rock",
            "singer-songwriter",
            "acoustic",
            "contemporary folk",
            "folk-punk",
            "anti-folk",
            "neofolk",
            "freak-folk",
        ],
    },
    {
        "name": "americana_roots",
        "display_name": "Americana / Roots",
        "description": "Americana, roots rock, bluegrass, old-time",
        "sort_order": 33,
        "members": [
            "americana",
            "roots",
            "roots rock",
            "bluegrass",
            "old-time",
            "rockabilly",
            "western swing",
        ],
    },
    # --- Reggae / Ska ---
    {
        "name": "reggae",
        "display_name": "Reggae / Ska",
        "description": "Reggae, ska, rocksteady, dancehall",
        "sort_order": 34,
        "members": [
            "reggae",
            "roots reggae",
            "ska",
            "rocksteady",
            "dancehall",
            "lovers rock",
            "dub",
            "two-tone",
            "2 tone",
        ],
    },
    # --- Classical ---
    {
        "name": "classical",
        "display_name": "Classical",
        "description": "Western classical music across all periods",
        "sort_order": 35,
        "members": [
            "classical",
            "baroque",
            "romantic",
            "renaissance",
            "contemporary classical",
            "early music",
            "modern classical",
            "minimalism",
            "opera",
            "chamber music",
            "orchestral",
            "choral",
            "symphony",
        ],
    },
    # --- World / International ---
    {
        "name": "african",
        "display_name": "African Music",
        "description": "African music — afrobeat, highlife, Afro-pop",
        "sort_order": 36,
        "members": [
            "african",
            "africa",
            "afrobeat",
            "afro-pop",
            "highlife",
            "soukous",
            "mali",
            "ethiopian",
            "fela kuti",
            "mbalax",
            "juju",
        ],
    },
    {
        "name": "latin",
        "display_name": "Latin Music",
        "description": "Latin, salsa, cumbia, tropical, reggaeton",
        "sort_order": 37,
        "members": [
            "latin",
            "salsa",
            "cumbia",
            "merengue",
            "bachata",
            "reggaeton",
            "latin pop",
            "tropical",
            "latin rock",
        ],
    },
    {
        "name": "brazilian",
        "display_name": "Brazilian Music",
        "description": "MPB, samba, bossa nova, tropicalia",
        "sort_order": 38,
        "members": [
            "brazilian",
            "brasil",
            "brazil",
            "mpb",
            "samba",
            "bossa nova",
            "tropicalia",
            "forro",
            "baiao",
        ],
    },
    {
        "name": "caribbean",
        "display_name": "Caribbean Music",
        "description": "Caribbean styles — calypso, soca, zouk, compas",
        "sort_order": 39,
        "members": [
            "caribbean",
            "calypso",
            "soca",
            "zouk",
            "compas",
            "cuban",
            "cuba",
        ],
    },
    {
        "name": "celtic_irish",
        "display_name": "Celtic / Irish",
        "description": "Celtic, Irish, Scottish traditional music",
        "sort_order": 40,
        "members": [
            "celtic",
            "irish",
            "scottish",
            "celtic folk",
        ],
    },
    {
        "name": "middle_eastern_jewish",
        "display_name": "Middle Eastern / Jewish",
        "description": "Middle Eastern, klezmer, Israeli, Mizrahi",
        "sort_order": 41,
        "members": [
            "middle eastern",
            "klezmer",
            "israeli",
            "jewish",
            "israel",
            "arabic",
            "turkish",
            "persian",
        ],
    },
    {
        "name": "world_music",
        "display_name": "World Music",
        "description": "Catch-all for world music, global, international",
        "sort_order": 42,
        "members": [
            "world",
            "world music",
            "international",
            "global",
        ],
    },
    # --- Singer-Songwriter / Vocal ---
    {
        "name": "singer_songwriter",
        "display_name": "Singer-Songwriter",
        "description": "Singer-songwriter, confessional, troubadour",
        "sort_order": 43,
        "members": [
            "singer-songwriter",
            "confessional",
        ],
    },
    {
        "name": "vocal_easy_listening",
        "display_name": "Vocal / Easy Listening",
        "description": "Vocal, crooner, lounge, easy listening, exotica",
        "sort_order": 44,
        "members": [
            "vocal",
            "easy listening",
            "lounge",
            "exotica",
            "adult contemporary",
        ],
    },
    # --- Decades ---
    {
        "name": "era_50s_60s",
        "display_name": "50s & 60s",
        "description": "Music from the 1950s and 1960s",
        "sort_order": 50,
        "members": [
            "50s",
            "60s",
            "oldies",
        ],
    },
    {
        "name": "era_70s",
        "display_name": "70s",
        "description": "Music from the 1970s",
        "sort_order": 51,
        "members": [
            "70s",
        ],
    },
    {
        "name": "era_80s",
        "display_name": "80s",
        "description": "Music from the 1980s",
        "sort_order": 52,
        "members": [
            "80s",
        ],
    },
    {
        "name": "era_90s",
        "display_name": "90s",
        "description": "Music from the 1990s",
        "sort_order": 53,
        "members": [
            "90s",
        ],
    },
    {
        "name": "era_2000s_plus",
        "display_name": "2000s+",
        "description": "Music from 2000 onwards",
        "sort_order": 54,
        "members": [
            "2000s",
            "2010s",
            "2020s",
        ],
    },
    # --- Descriptors / Moods ---
    {
        "name": "female_vocalists",
        "display_name": "Female Vocalists",
        "description": "Tracks tagged with female vocalist descriptors",
        "sort_order": 60,
        "members": [
            "female vocalists",
            "female vocalist",
            "female",
            "women",
        ],
    },
    {
        "name": "instrumental",
        "display_name": "Instrumental",
        "description": "Instrumental music (no vocals)",
        "sort_order": 61,
        "members": [
            "instrumental",
            "guitar",
            "piano",
            "saxophone",
            "trumpet",
        ],
    },
    {
        "name": "soundtrack_score",
        "display_name": "Soundtrack / Score",
        "description": "Film soundtracks, TV scores, video game music",
        "sort_order": 62,
        "members": [
            "soundtrack",
            "film score",
            "video game music",
            "musical",
        ],
    },
    {
        "name": "comedy_spoken",
        "display_name": "Comedy / Spoken Word",
        "description": "Comedy, spoken word, poetry",
        "sort_order": 63,
        "members": [
            "comedy",
            "spoken word",
            "poetry",
        ],
    },
    {
        "name": "cajun_zydeco",
        "display_name": "Cajun / Zydeco",
        "description": "Cajun, zydeco, Louisiana music",
        "sort_order": 45,
        "members": [
            "cajun",
            "zydeco",
            "louisiana",
            "swamp pop",
            "swamp rock",
        ],
    },
    {
        "name": "gospel_spiritual",
        "display_name": "Gospel / Spiritual",
        "description": "Gospel, spiritual, Christian music",
        "sort_order": 46,
        "members": [
            "gospel",
            "spiritual",
            "christian",
            "christian rock",
            "worship",
        ],
    },
]
